export enum ServerEvents {
  TOGGLE_CREATE_CHANNEL_MODAL = 'TOGGLE_CREATE_CHANNEL_MODAL',
  TOGGLE_CREATE_CATEGORY_MODAL = 'TOGGLE_CREATE_CATEGORY_MODAL',
  TOGGLE_INVITE_MODAL = 'TOGGLE_INVITE_MODAL',
  TOGGLE_SERVER_SETTINGS_MODAL = 'TOGGLE_SERVER_SETTINGS_MODAL',
}
